---
Name: cookie-policy-notification
---

PageController:
  extensions:
    - Novatio\CookiePolicy\CookiePolicy

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Novatio\CookiePolicy\SiteConfigCookiePolicy
